# Generated by Django 3.1 on 2020-12-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badgename', models.CharField(blank=True, max_length=122, null=True)),
                ('badgetype', models.CharField(blank=True, max_length=122, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=122, null=True)),
                ('picture', models.CharField(blank=True, max_length=122, null=True)),
                ('email', models.CharField(blank=True, max_length=122, null=True)),
                ('dept', models.CharField(blank=True, max_length=122, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RnR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empsent', models.CharField(blank=True, max_length=122, null=True)),
                ('badgetype', models.CharField(blank=True, max_length=122, null=True)),
                ('badgename', models.CharField(blank=True, max_length=122, null=True)),
                ('message', models.CharField(blank=True, max_length=122, null=True)),
                ('emprecvd', models.CharField(blank=True, max_length=122, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendorname', models.CharField(blank=True, max_length=122, null=True)),
                ('vendorcompany', models.CharField(blank=True, max_length=122, null=True)),
                ('empsent', models.CharField(blank=True, max_length=122, null=True)),
                ('badgetype', models.CharField(blank=True, max_length=122, null=True)),
                ('badgename', models.CharField(blank=True, max_length=122, null=True)),
                ('message', models.CharField(blank=True, max_length=122, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
