# Generated by Django 3.1.5 on 2021-01-25 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thankyousys', '0002_empuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empuser',
            old_name='name',
            new_name='username',
        ),
    ]
