# Generated by Django 3.1.5 on 2021-01-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thankyousys', '0003_auto_20210125_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgesSentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(blank=True, max_length=122, null=True)),
                ('badge_title', models.CharField(blank=True, max_length=122, null=True)),
                ('Receiver', models.CharField(blank=True, max_length=122, null=True)),
            ],
        ),
    ]
